- src/css/sass/components.scss
- src/css/sass/components/filters.scss
- src/css/sass/components/projects.scss
- src/js/settings.js
- src/js/templates/projects/layerControl.html
- src/js/templates/responses/embed-multi.html
- src/js/views/maps/cartodb-layer.js
- src/js/views/maps/multi-map.js
- src/js/views/projects/datalayers/survey.js
- src/js/views/projects/datalayers/survey/settings-survey.js
- src/js/views/projects/projects.js
- src/js/views/surveys/multi.js
- Adds layer controls for carto layers
- Adds support for custom baselayers
- Adds '
Also adds a couple params for foreign layers:
- `noLegend: true` -- don't show the layerControl
- `disableGrid: true` -- don't add a UTF grid
- `state: 'inactive'` -- The layer starts "turned off". Renders the control, but doesn't add the layer to the map
> Gtech: add carto layer legends and improve styling

- src/css/sass/components.scss
- src/css/sass/components/filters.scss
- src/css/sass/components/projects.scss
- src/js/templates/filters/filters.html
- src/js/templates/filters/question-filters.html
- src/js/templates/projects/surveys/legend.html
- src/js/templates/projects/surveys/settings-survey.html
- src/js/templates/surveys/layerFilter.html
- src/js/views/projects/datalayers/survey.js
- src/js/views/projects/datalayers/survey/settings-survey.js
- src/js/views/responses/filter.js
- src/js/views/responses/responses.js
- src/js/views/surveys/legend.js
Creates a new `LegendView` that is used by both projects and surveys. It's got some dark corners -- since the two use different naming and data structures, compromises were necessary. 
A next step refactor would make a view for each question in the filter, which would then also replace the legend.
> Use the same legend interface on projects and surveys

- src/js/views/maps/cartodb-layer.js
- src/js/views/maps/multi-map.js
I could do this as an options object (it's a bit mystery meat) but this does the trick
> Fix an issue where carto grids wouldn't be added at far zooms

- src/js/views/projects/datalayers/survey.js
This avoid URL length issues for involved layer definitions.
> Use POST for specifying LocalData layer definitions

- src/css/sass/components.scss
Also adds a subtle border in the same style used for responses and filters to distinguish the box from the map (addresses #509)
> Let the control pane shrink when there's less content

- src/js/views/maps/cartodb-layer.js
- src/js/views/projects/datalayers/survey.js
- src/js/views/projects/projects.js
Fixes #510
Large zIndex values (eg `500`) didn't appear to mess with UI.
> Support explicit zIndexes for project layers

- src/css/sass/components/projects.scss
- src/css/sass/utils.scss
- src/js/templates/projects/reports.html
- src/js/templates/projects/surveys/stats-survey.html
- src/js/views/projects/reports.js
Currently a pulsing circle (5th one here http://tobiasahlin.com/spinkit/) in our $thinpink color. 
Also expands width of reports page so clients have more flexibility on how it's displayed.
> Add a subtle loading indicator to reports page

- src/css/sass/components.scss
- src/css/sass/components/projects.scss
- src/js/templates/projects/surveys/loading.html
- src/js/views/surveys/multi.js
Surveys that have non-trivial numbers of entries take a couple seconds to load (because we wait for all the settings -- including stats) before rendering. This PR adds a loading placeholder for each survey.
Hard to get a good screenshot for this... I should figure out how to make animated gifs
> Show a loading indicator on project pages

- src/css/sass/components/surveys.scss
- src/js/templates/responses/item.html
- src/js/views/projects/datalayers/survey.js
- src/js/views/projects/datalayers/survey/object-view.js
- src/js/views/projects/projects.js
- src/js/views/responses/item.js
- src/js/views/responses/list.js
Lets us hide, show, reword, and reorder questions in the projects display by setting `options. explorationControlsItem` to `true`.
Also adds a bit of spacing between responses so they scan nicely:
> Let projects specify display of questions in the item view

- src/css/sass/components/filters.scss
IE does not support `display: initial`
I searched and this appears to be the only place we used it.
> Fix a problem where settings button does not work on IE 

- src/js/views/projects/datalayers/survey.js
The initializers for the survey model and forms collection both perform the type of fetch we need, so we can avoid a second, explicit fetch.
> Avoid fetching Survey and Forms twice

- src/js/models/responses.js
- src/js/views/responses/filter.js
- src/js/views/responses/item.js
- src/js/views/responses/responses.js
- src/js/views/responses/review.js
- src/js/views/surveys.js
- src/js/views/surveys/stats-collector.js
Avoid review-related requests unless we really need them, and make cheaper requests when we do.
Pass stats around instead of making multiple requests for them.
Make the review workflow a little more robust.
/cc @hampelm
> Organize api requests

- src/js/templates/surveys/zone-editor.html
- src/js/views/surveys/settings.js
- src/js/views/surveys/zone-editor.js
Fixes #581 
Basically, we were attaching leaflet layers to the zones attribute in the survey model. Backbone can't and shouldn't save them (JSON serialization problem). We used to sanitize them before saving, but when the zone editor was moved out to a new view, we lost an easy way to sanitize.
> Fix zone save breaking settings save

- src/js/templates/cartodb-info.html
- src/js/views/maps/cartodb-layer.js
- src/js/views/projects/projects.js
Pittsburgh needs a specific message to appear for some lots. 
This is a super hacky first take. If we need to do this twice, we should abstract this into project config. Here's a possible strategy: 
* Craft the carto query to return a boolean if the message should appear
* Add a `notes` config to the `projects` config.
```
notes: [{
field: 'myCartoBooleanToShowMessage',
values: [true],
note: 'My excellent message'
}, {
field: 'myCartoBooleanToShowMessage',
values: [false, 'dogs'],
note: 'Cats rule'
}]
``` 
And in the carto template, iterate over the notes and display them if the values match.
> Add a context-specific note for Pittsburgh carto layer objects

- src/js/templates/projects/surveys/checkbox-styles.mss
- src/js/templates/projects/surveys/simple-styles.mss
We did not provide MultiLineString rules in all style templates, so those geometries would disappear in some project map views. This should apply styles consistently across LineString and MultiLineString geometries.
/cc @hampelm
> Style MultiLineString geometries in project templates

- src/css/sass/components.scss
- src/js/settings.js
- src/js/views/map.js
Adds a simple control to produce a PDF of the currently focused map region using Datamade's Lascaux.
> Add a print control to the map

- src/js/lib/autolinker.js
- src/js/templates/responses/item.html
- src/js/views/responses/item.js
Turn URLs and other would-be links into anchor elements.
Fixes #602 
/cc @hampelm
> Use Autolinker.js to linkify text fields

- src/js/models/responses.js
- src/js/views/projects/datalayers/survey.js
- src/js/views/responses/responses.js
Specify sort order for entries in the object details view.
Maintain specified sort order in a Response collection
> Show a parcel's entries in reverse chronological order

- src/css/sass/components/editor.scss
- src/js/templates/surveys/form-editor.html
- src/js/views/builder.js
Instead, give a warning and highlight the offending fields. Fixes #359.
> Don't let users submit questions or answers that are blank

- src/css/sass/components/surveys.scss
- src/js/templates/responses/item.html
- src/js/views/responses/item.js
A couple changes in the way editing responses works: 
- The edit view shows all possible questions (ignoring skip logic), giving survey managers more control. A future version could better visually distinguish question hierarchy. 
- We use PUT instead of PATCH to support removing answers
> Use PUT instead of PATCH to edit response answers.

- src/js/templates/projects/surveys/explore-sparse-styles.mss
- src/js/views/projects/project-utils.js
- src/js/views/projects/projects.js
Improve balance of points against other features when zoomed out (helps Lots to Love and Walkscope).
Add a style template for projects with sparse polygon data mixed with points, emphasizing polygon outlines at low zooms to improve balance.
Update Lots to Love styling based on feedback from users via GTECH.
> Lots to Love styling

- .gitignore
- src/js/settings.js
- src/js/views/map.js
- src/js/views/maps/feature-tiles-layer.js
- src/js/views/projects/datalayers/survey.js
This should help a little with grid caching, since the grid response content will be the same regardless of load order/etc. With JSONP, the callback names can change, leading to cache misses.
This change depends on https://github.com/LocalData/localdata-tiles/pull/158
> Avoid using JSONP for grids when the browser will support CORS requests

- src/js/views/projects/projects.js
Nodetiles uses the `line-color` style to decide if a geometry should be rendered onto the UTF grid, so we should avoid setting that style for features that we really intend to be invisible/omitted. This reduces the grid file size for allegheny parcel feature tiles to about a quarter of the previous size.
/cc @hampelm
> Avoid rendering grid data for invisible parcels

- src/js/views/root.js
The order of operations meant the template wasn't in place to hide / show the user tools.
> Replace missing userbar

- src/js/models/forms.js
- src/js/templates/responses/item.html
- src/js/views/responses/item.js
Show the "parent question" of each multiple choice question. 
Eg if the question is "Siding type" and the answers are:
* Brick
* Vinyl 
* None
The result will display in the detail view as 
```
Siding type
Brick
yes
```
Not the cleanest (ideally we could just say "siding type: brick") but this keeps the detail view consistent with the deep dive and exports.
> Add clarity to multiple choice questions
